export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

export const APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST';
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';

export const CURRENTAPPOINTMENT_REQUEST = 'CURRENTAPPOINTMENT_REQUEST';
export const CURRENTAPPOINTMENT_SUCCESS = 'CURRENTAPPOINTMENT_SUCCESS';
export const CURRENTAPPOINTMENT_ERROR = 'CURRENTAPPOINTMENT_ERROR';

export const UPLOADPRESCRIPTION_REQUEST = 'UPLOADPRESCRIPTION_REQUEST';
export const UPLOADPRESCRIPTION_SUCCESS = 'UPLOADPRESCRIPTION_SUCCESS';
export const UPLOADPRESCRIPTION_ERROR = 'UPLOADPRESCRIPTION_ERROR';