import Head from "next/head";
// import { useRouter } from "next/router";
// import { useEffect } from "react";
import { Container } from "../components/pageComponents/global/style";
import Helmet from "../components/utils/Header/Helmet";
import Landing from "./Landing";
import Login from "./Login";
import { useSelector } from "react-redux";
import SignUp from "./SignUp";

export default function Home() {
  // let bool = false;
  const isSignedIn = useSelector((state) => state.signup.success);
  const isLoggedIn = useSelector((state) => state.login.success);
  // const dispatch = useDispatch();

  // dispatch(getAppointments({ id: id }));

  return (
    <div>
      <Head>
        <title>DOC-UPI-Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Helmet />
        {/* {loggedIn ? <Landing /> : <Login />} */}
        {isLoggedIn && <Landing />}
        {isSignedIn && !isLoggedIn && <Login />}
        {!isSignedIn && !isLoggedIn && <SignUp />}
      </Container>
    </div>
  );
}
